# Generated by Django 5.1.7 on 2025-04-30 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': 'User Info', 'verbose_name_plural': 'User Info'},
        ),
        migrations.AddField(
            model_name='user_info',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
