# Generated by Django 5.1.7 on 2025-04-30 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc_project', '0002_alter_user_info_options_user_info_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={},
        ),
        migrations.AddField(
            model_name='user_info',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user_info',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('merchandising', 'Merchandising'), ('service', 'Service'), ('technical', 'Technical')], max_length=50)),
                ('description', models.TextField()),
                ('voice_feedback', models.FileField(blank=True, null=True, upload_to='feedback/voice/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('is_valid', models.BooleanField(blank=True, null=True)),
                ('executive_approval', models.BooleanField(blank=True, null=True)),
                ('date_of_issue', models.DateField()),
                ('problem_statement', models.TextField()),
                ('fact_check', models.TextField()),
                ('root_cause_analysis', models.TextField()),
                ('corrective_action', models.TextField()),
                ('preventive_action', models.TextField()),
                ('proposals_remarks', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_details', to='ccc_project.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='feedback/photos/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ccc_project.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_file', models.FileField(upload_to='feedback/solutions/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_files', to='ccc_project.feedback')),
            ],
        ),
    ]
